---
id: burikaigi2025-lt-ossgate
base_name: burikaigi2025-lt-ossgate
tags: [burikaigi, oss_gate, clear-code]
presentation_date: 
presentation_start_time: 
presentation_end_time: 
version: 1.0.0
licenses: [CC-BY-SA-4.0]
slideshare_id: 
speaker_deck_id: 
vimeo_id: 
youtube_id: 
width: 1920
height: 1080
source_code_uri: https://github.com/daipom/burikaigi2025-lt-ossgate
author:
  markup_language: :markdown
  name: Daijiro Fukuda
  email: fukuda@clear-code.com
  rubygems_user: daipom
  slideshare_user: 
  speaker_deck_user: 
